import {createClient} from 'jsr:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type','Content-Type':'application/json'};
const roleLevel=(role:string)=>{const r=(role||'').toLocaleLowerCase('ro-RO');if(r.includes('coordonator')||['admin','owner'].includes(r))return 7;if(r==='lider')return 6;if(['colider','co-lider','co lider'].includes(r))return 5;if(r.includes('manager'))return 4;if(r.includes('familia'))return 3;if(r.includes('sef')||r.includes('șef'))return 2;return 1};
const reply=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:cors});
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return reply({error:'Method not allowed'},405);try{
 const body=await req.json(),token=body.access_token;if(!token)return reply({error:'Sesiunea Discord lipsește. Autentifică-te din nou.'},401);
 const me=await fetch('https://discord.com/api/v10/users/@me',{headers:{Authorization:`Bearer ${token}`}});if(!me.ok)return reply({error:'Sesiunea Discord nu mai este validă.'},401);const du=await me.json();
 const keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')??'{}'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||keys.default;const db=createClient(Deno.env.get('SUPABASE_URL')!,key);const {data:panelDiscordConfig}=await db.from('discord_panel_config').select('*').eq('id',1).maybeSingle();
 const {data:user}=await db.from('users').select('*').eq('discord_id',du.id).single();if(!user)return reply({error:'Utilizatorul nu există în panel.'},403);const level=roleLevel(user.role||user.default_role);
 const own=async(id:string)=>{const {data,error}=await db.from('community_posts').select('*').eq('id',id).maybeSingle();if(error)throw error;if(!data)throw new Error('Postarea nu mai există în baza de date. Reîncarcă pagina.');if(level!==7&&String(data.author_discord_id)!==String(du.id))throw new Error('Poți administra numai postările tale.');return data};
 if(body.action==='create'){
  if(level<4)return reply({error:'Publicarea este disponibilă de la Manager în sus.'},403);if(!['family','mechanics'].includes(body.audience))throw new Error('Alege audiența.');
  const {data:post,error}=await db.from('community_posts').insert({post_type:body.post_type,audience:body.audience,title:body.title,content:body.content,author_discord_id:du.id,author_name:user.display_name||user.username}).select().single();if(error)throw error;
  if(body.post_type==='poll'){const options=(body.options||[]).map((x:string,i:number)=>({post_id:post.id,option_text:x,position:i}));const {error:e}=await db.from('community_poll_options').insert(options);if(e)throw e}
  const discordMessageId=await notifyDiscord(post,body.options||[]);if(discordMessageId)await db.from('community_posts').update({discord_message_id:discordMessageId}).eq('id',post.id);return reply({post});
 }
 if(body.action==='update'){const post=await own(body.post_id);const {error}=await db.from('community_posts').update({title:body.title,content:body.content,updated_at:new Date().toISOString()}).eq('id',body.post_id);if(error)throw error;if(post.post_type==='poll'&&Array.isArray(body.options)){if(body.options.length<2)throw new Error('Sondajul trebuie să aibă minimum două opțiuni.');const {data:existing}=await db.from('community_poll_options').select('option_text').eq('post_id',body.post_id).order('position');const changed=JSON.stringify((existing||[]).map((x:any)=>x.option_text))!==JSON.stringify(body.options);if(changed){const {error:deleteOptionsError}=await db.from('community_poll_options').delete().eq('post_id',body.post_id);if(deleteOptionsError)throw deleteOptionsError;const {error:insertOptionsError}=await db.from('community_poll_options').insert(body.options.map((text:string,position:number)=>({post_id:body.post_id,option_text:text,position})));if(insertOptionsError)throw insertOptionsError}}return reply({ok:true})}
 if(body.action==='delete'){const post=await own(body.post_id);const {data:deleted,error}=await db.from('community_posts').delete().eq('id',body.post_id).select('id');if(error)throw error;if(!deleted?.length)throw new Error('Supabase nu a șters postarea. Verifică politicile bazei de date.');if(post.discord_message_id){const webhook=post.audience==='family'?(panelDiscordConfig?.family_webhook_url||Deno.env.get('DISCORD_FAMILY_WEBHOOK_URL')):(panelDiscordConfig?.mechanics_webhook_url||Deno.env.get('DISCORD_MECHANICS_WEBHOOK_URL'));if(webhook)await fetch(`${webhook}/messages/${post.discord_message_id}`,{method:'DELETE'})}return reply({ok:true,deleted_id:body.post_id})}
 if(body.action==='marketplace_delete'){const table=body.table;if(!['marketplace','marketplace_ilegal'].includes(table))throw new Error('Tabel Marketplace invalid.');const {data:item,error:itemError}=await db.from(table).select('id,created_by_discord_id').eq('id',body.item_id).maybeSingle();if(itemError)throw itemError;if(!item)throw new Error('Anunțul nu mai există.');if(level!==7&&String(item.created_by_discord_id||'')!==String(du.id))return reply({error:'Poți șterge numai anunțurile publicate de tine.'},403);const {data:deleted,error}=await db.from(table).delete().eq('id',body.item_id).select('id');if(error)throw error;if(!deleted?.length)throw new Error('Anunțul nu a fost șters din baza de date.');return reply({ok:true,deleted_id:body.item_id})}
 if(body.action==='react'){const key={post_id:body.post_id,user_discord_id:du.id,reaction:body.reaction};const {data}=await db.from('community_reactions').select('id').match(key).maybeSingle();const q=data?db.from('community_reactions').delete().eq('id',data.id):db.from('community_reactions').insert(key);const {error}=await q;if(error)throw error;return reply({ok:true})}
 if(body.action==='vote'){const {data:option}=await db.from('community_poll_options').select('post_id').eq('id',body.option_id).single();if(!option||option.post_id!==body.post_id)throw new Error('Opțiune invalidă.');const {error}=await db.from('community_poll_votes').upsert({post_id:body.post_id,option_id:body.option_id,user_discord_id:du.id},{onConflict:'post_id,user_discord_id'});if(error)throw error;await updateDiscordPoll(body.post_id);return reply({ok:true})}
 return reply({error:'Acțiune necunoscută.'},400);
 async function notifyDiscord(post:any,options:string[]){const family=post.audience==='family',url=family?(panelDiscordConfig?.family_webhook_url||Deno.env.get('DISCORD_FAMILY_WEBHOOK_URL')):(panelDiscordConfig?.mechanics_webhook_url||Deno.env.get('DISCORD_MECHANICS_WEBHOOK_URL'));if(!url)return null;const site=(panelDiscordConfig?.panel_public_url||Deno.env.get('PANEL_PUBLIC_URL')||'https://lttlmario.github.io/panel-mafie').replace(/\/$/,'');const postUrl=`${site}/anunturi.html?post=${post.id}`,roleId=(family?panelDiscordConfig?.family_role_id:panelDiscordConfig?.mechanics_role_id)||Deno.env.get(family?'DISCORD_FAMILY_ROLE_ID':'DISCORD_MECHANICS_ROLE_ID')||(family?'1526734716760227930':'1526734796125114488');const fields=[] as Array<{name:string,value:string}>;if(post.post_type==='poll'&&options.length)fields.push({name:'Rezultate live',value:options.map(x=>`▫️ ${x} — 0 voturi (0%)`).join('\n')});fields.push({name:post.post_type==='poll'?'🗳️ Votează în panel':'💬 Răspunde în panel',value:`[Deschide postarea](${postUrl})`});const sent=await fetch(`${url}?wait=true`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({embeds:[{title:post.title,description:post.content,color:family?15548997:3447003,fields,url:postUrl,footer:{text:`${post.post_type==='poll'?'Sondaj':post.post_type==='question'?'Întrebare':'Anunț'} • ${post.author_name}`}}]})});const message=sent.ok?await sent.json():null;await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:`<@&${roleId}>`,allowed_mentions:{roles:[roleId]}})});return message?.id||null}
 async function updateDiscordPoll(postId:string){
  const {data:post}=await db.from('community_posts').select('*').eq('id',postId).single();if(!post?.discord_message_id)return;
  const [{data:options},{data:votes}]=await Promise.all([db.from('community_poll_options').select('*').eq('post_id',postId).order('position'),db.from('community_poll_votes').select('*').eq('post_id',postId)]);
  const total=votes?.length||0,result=(options||[]).map((o:any)=>{const count=(votes||[]).filter((v:any)=>v.option_id===o.id).length,percent=total?Math.round(count*100/total):0;return `▫️ ${o.option_text} — ${count} voturi (${percent}%)`}).join('\n');
  const family=post.audience==='family',url=family?(panelDiscordConfig?.family_webhook_url||Deno.env.get('DISCORD_FAMILY_WEBHOOK_URL')):(panelDiscordConfig?.mechanics_webhook_url||Deno.env.get('DISCORD_MECHANICS_WEBHOOK_URL'));if(!url)return;const site=(panelDiscordConfig?.panel_public_url||Deno.env.get('PANEL_PUBLIC_URL')||'https://lttlmario.github.io/panel-mafie').replace(/\/$/,''),postUrl=`${site}/anunturi.html?post=${post.id}`;
  await fetch(`${url}/messages/${post.discord_message_id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({embeds:[{title:post.title,description:post.content,color:family?15548997:3447003,url:postUrl,fields:[{name:`Rezultate live • ${total} voturi`,value:result||'Încă nu există voturi.'},{name:'🗳️ Votează în panel',value:`[Deschide sondajul](${postUrl})`}],footer:{text:`Sondaj • ${post.author_name}`}}]})})
 }
 }catch(e){console.error(e);return reply({error:e instanceof Error?e.message:'Eroare necunoscută.'},400)}});
